// Hand-curated one-liners for company pages. Keys are lowercased company
// names matching the `companies.name` column. Missing entries render
// nothing on the page — falls back gracefully.
//
// Replace with a Supabase `description` column once we backfill in the DB.
export const COMPANY_DESCRIPTIONS: Record<string, string> = {
  'anthropic':    'AI safety company building Claude, a family of large language models focused on helpful, harmless, and honest behavior.',
  'openai':       'AI research and deployment company behind ChatGPT, GPT-5, and the OpenAI API platform.',
  'stripe':       'Payments infrastructure for the internet — millions of businesses use Stripe to accept payments and manage their finances online.',
  'databricks':   'Unified data and AI platform built on the lakehouse architecture; created Apache Spark and MLflow.',
  'anduril':      'Defense technology company building autonomous systems for the US and allied militaries.',
  'palantir':     'Builds software platforms (Foundry, Gotham, AIP) for data integration, analytics, and AI deployment in enterprise and government.',
  'cursor':       'AI code editor; a VS Code fork tightly integrated with frontier LLMs for autocomplete, multi-file edits, and codebase chat.',
  'linear':       'Issue tracking and project management tool designed for high-velocity software teams.',
  'vercel':       'Frontend cloud platform; the company behind Next.js and the v0 AI design tool.',
  'notion':       'All-in-one workspace combining notes, docs, wikis, and project management with embedded AI.',
  'figma':        'Browser-based collaborative design tool for UI/UX, prototyping, and (more recently) AI-assisted design.',
  'canva':        'Online graphic design platform with templates, photos, and AI tools used by 220M+ people monthly.',
  'replit':       'Browser-based IDE and deployment platform with an AI agent that can build full apps from prompts.',
  'perplexity':   'AI-powered answer engine combining search and large language models, with citations.',
  'mistral':      'Paris-based AI lab building open-source and commercial frontier models; major European AI champion.',
  'harvey':       'AI for elite law firms — domain-specific large language models for legal research, drafting, and analysis.',
  'sierra':       'Conversational AI agents for customer experience, founded by Bret Taylor (ex-Salesforce, OpenAI board chair) and Clay Bavor.',
  'writer':       'Generative AI platform for enterprise teams, with custom models trained on company data.',
  'cohere':       'Enterprise-focused AI company building LLMs and the Command, Embed, and Rerank model families.',
  'roblox':       'Online platform and game creation system where users build and play games made by other users; 80M+ DAU.',
  'mongodb':      'Document-oriented NoSQL database with Atlas, a fully managed cloud database service.',
  'cloudflare':   'Global cloud network providing CDN, security, DDoS protection, Workers serverless compute, and AI inference.',
  'datadog':      'Monitoring and analytics platform for cloud applications, infrastructure, logs, and security.',
  'okta':         'Identity and access management; SSO, MFA, and lifecycle management for enterprise workforces.',
  'twilio':       'Customer engagement platform with APIs for SMS, voice, email, and AI-driven communications.',
  'atlassian':    'Maker of Jira, Confluence, and Bitbucket — work management and collaboration tools used by software and DevOps teams.',
  'gitlab':       'DevSecOps platform combining source control, CI/CD, security scanning, and deployment in one application.',
  'lyft':         'Ridesharing, bikes, scooters, and autonomous transportation operating across North America.',
  'pinterest':    'Visual discovery and inspiration platform; users save and discover ideas through images and videos.',
  'reddit':       'Network of communities organized by interest where users post, comment, and vote on content.',
  'airbnb':       'Online marketplace for short-term homestays and experiences in 220+ countries.',
  'doordash':     'On-demand local logistics platform; food, grocery, and retail delivery across North America and beyond.',
  'snap':         'Maker of Snapchat, AR glasses (Spectacles), and AI-driven AR creator tools.',
  'servicenow':   'Cloud-based workflow automation platform for IT, HR, customer service, and security operations.',
  'workday':      'Enterprise cloud applications for finance and human resources.',
  'plaid':        'Financial data network connecting bank accounts to apps; powers most US fintech.',
  'temporal':     'Open-source durable execution platform for building reliable distributed systems and AI agents.',
  'supabase':     'Open-source Firebase alternative — Postgres, auth, storage, and edge functions with a developer-friendly API.',
  'discord':      'Voice, video, and text chat for communities; originally gaming-focused, now widely used by creators and friend groups.',
  'github':       'World\'s largest code-hosting platform and home of GitHub Copilot, the most popular AI coding assistant.',
  'shopify':      'Commerce platform; powers millions of businesses with online stores, point-of-sale, and shipping.',
  'meta':         'Parent of Facebook, Instagram, WhatsApp, and Reality Labs (AR/VR + Llama AI models).',
  'microsoft':    'Maker of Windows, Office, Azure, GitHub, and Copilot — and largest external shareholder in OpenAI.',
  'apple':        'Maker of the iPhone, Mac, iPad, Apple Watch, and Apple Intelligence; world\'s most valuable consumer hardware company.',
  'google':       'Search, Android, YouTube, Workspace, Google Cloud, and Gemini AI under parent Alphabet.',
  'netflix':      'Streaming entertainment service with original films, series, and games in 190+ countries.',
};
