// Maps company name (as stored in Supabase) → primary domain for Apollo enrichment.
// Apollo's org enrich API returns the best match for a given domain.
export const DOMAIN_MAP: Record<string, string> = {
  'Anthropic':        'anthropic.com',
  'OpenAI':           'openai.com',
  'Cursor':           'cursor.com',
  'Replit':           'replit.com',
  'Vercel':           'vercel.com',
  'Databricks':       'databricks.com',
  'Snowflake':        'snowflake.com',
  'Stripe':           'stripe.com',
  'Coinbase':         'coinbase.com',
  'Figma':            'figma.com',
  'Notion':           'notion.so',
  'Linear':           'linear.app',
  'Airtable':         'airtable.com',
  'Retool':           'retool.com',
  'Loom':             'loom.com',
  'Miro':             'miro.com',
  'Canva':            'canva.com',
  'Brex':             'brex.com',
  'Rippling':         'rippling.com',
  'Wise':             'wise.com',
  'Spotify':          'spotify.com',
  'Datadog':          'datadoghq.com',
  'Cloudflare':       'cloudflare.com',
  'MongoDB':          'mongodb.com',
  'Confluent':        'confluent.io',
  'HashiCorp':        'hashicorp.com',
  'GitLab':           'gitlab.com',
  'Atlassian':        'atlassian.com',
  'Okta':             'okta.com',
  'Twilio':           'twilio.com',
  'Asana':            'asana.com',
  'UiPath':           'uipath.com',
  'Samsara':          'samsara.com',
  'Lyft':             'lyft.com',
  'Scale AI':         'scale.com',
  'Cohere':           'cohere.com',
  'Mistral':          'mistral.ai',
  'Perplexity':       'perplexity.ai',
  'Harvey':           'harvey.ai',
  'Glean':            'glean.com',
  'Temporal':         'temporal.io',
  'dbt Labs':         'getdbt.com',
  'Hex':              'hex.tech',
  'Modal':            'modal.com',
  'Weights & Biases': 'wandb.ai',
  'Hugging Face':     'huggingface.co',
  'Together AI':      'together.ai',
  'Netflix':          'netflix.com',
  'Roblox':           'roblox.com',
  'ServiceNow':       'servicenow.com',
  'Workday':          'workday.com',
  'Microsoft':        'microsoft.com',
  'Apple':            'apple.com',
  'Meta':             'meta.com',
  'Google':           'google.com',
  'Salesforce':       'salesforce.com',
  'HackerRank':       'hackerrank.com',
};
